version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: NzkxODQxMzkwMTQ5MjM4ODI0.X-VBww.lVnK22vUglkQZTfcnfFtncMwUGM
      ENABLE_RANDOM_JOINS: "True"
      LOGGING_CHANNEL: <your-logging-textchannel-id-as-integer>
