version: "3"
services:
  drachenlord:
    build: .
    environment:
      DISCORD_API_TOKEN: <MTIzMDg2MzI5NTAyNDcyNjAyNg.Gd3hz7.OJA5XzMpO5PF43vCuGGEb1a_i_29rjryLa4fPA>
      ENABLE_RANDOM_JOINS: "True"
      LOGGING_CHANNEL: <your-logging-textchannel-id-as-integer>
